### ISSUE TITLE
Change "Rbnev" to "Rbenv"

### ISSUE THREAD

**Issue by otherchris** [cheapwebmonkey/dev-design-resources#5]
Or maybe "rbenv"? not sure about capitalizing repo names at the beginning of a sentence
![rbnev](https://cloud.githubusercontent.com/assets/9843291/8712464/7a48344a-2b2a-11e5-97f6-b5e2f63fb4df.png)

**Comment by cheapwebmonkey** [comment]
Yean all lower case - good spot
